= Jogit

A bad toy git web interface. Not scallable and not secure.

== Setup for development

=== Install OpenJDK 11
```
sudo apt update
sudo apt-get install openjdk-11-jdk
```

=== Install openssh-server
The application requires SSH access, so that users can
access their git repositories.

If installing openssh-server on your own computer, make sure your
port 22 is NOT open, so that nobody can access your computer
using SSH from outside.

```
sudo apt install openssh-server
```

=== Create the application directory structure
```
mkdir /jogit
```

=== Install Docker
```
sudo apt-get install docker
sudo apt-get install docker-compose
```

=== Running the database and the Envoy proxy
Start the docker daemon if it's not running

```
sudo service docker start
```

```
sudo docker-compose up
```

Docker compose will:

- run Postgres, create a database "jogitdev" and a user "postgres" with password
"c4ef37c0fbd747da1c63c0f87d7c62df" and run on port 8092.
- run the Envoy proxy, required for gRPC web.

When the deployment is successful, you can access Envoy's
admin interface at localhost:9902, and the backend server
at localhost:8080

=== Create a configuration file
* Copy conf.example.json to conf.secret.json (it will not be committed because it's in .gitignore)
* If you've changed the port from conf.example.json, you need to update it in
front-envoy.yaml as well.
* Copy conf.example.json to test-conf.secret.json (it will not be committed because it's in .gitignore)
* Export the variable JOGIT_CONF and JOGIT_TEST_CONF
```
export JOGIT_CONF=<path to conf.secret.json>
export JOGIT_TEST_CONF=<path to test-conf.secret.json>
```

=== Setup the database schema
Run schema/schema.sql.

== Building

=== Generate gRPC code & build
```
./gradlew build
```

=== Launch tests
```
./gradlew clean test
```

=== Run the application
```
./gradlew clean run
```

== Setup in IntelliJ
=== Setup modules
* Open File -> Project Structure -> Project
* Select Project SDK 11
* Select Project language level 11
* Set the Project compiler output to ./build

=== Import Gradle Project
Right click on build.gradle, click on "Import Gradle project", this will
install all dependencies and make the Gradle menu available.

== Debugging in IntelliJ
Setup a new configuration:

- Type: Application
- Main class: io.vertx.core.Launcher
- Program arguments: run com.example.starter.MainVerticle
- use classpath of module: starter.main

== How to setup a git repository accessible through SSH
These steps are done (or will be done...) by the application when creating a user
and creating repositories.

=== Create a git user
```
sudo adduser gituser
su gituser
cd
mkdir .ssh && chmod 700 .ssh
touch .ssh/authorized_keys && chmod 600 .ssh/authorized_keys
exit
```
Warning: if the .ssh folder and its children are not the property of gituser:gituser,
login using SSH will always ask for the user's password.

=== Create a repository
Create the folder and init the git repository:
```
cd /srv/jogit/git
mkdir gituser
sudo chown -R gituser:gituser gituser
cd gituser
su gituser
cd /srv/jogit/git/gituser
mkdir testrepository.git
cd testrepository.git
git init --bare
exit
```

Create a user group for all groups that are allowed to write to the repository:
```
sudo groupadd testrepository
sudo chown -R gituser:testrepository testrepository.git
sudo usermod -a -G testrepository gituser
```

=== Add your own public key to the git user's authorized_keys
```
sudo bash -c 'cat ~/.ssh/id_rsa.pub >> /home/gituser/.ssh/authorized_keys'
```

=== Disallow accessing the shell as the git user

```
sudo chsh gituser -s $(which git-shell)
```

=== Disallow port forwarding
Prepend this to the entry in /home/git/authorized_keys:
```
no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty
```

=== Use the repository
```
git clone gituser@localhost:/srv/jogit/git/testuser/testrepository.git
cd testrepository
touch README
git add .
git commit -am "create README file"
git push
```

