// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: git-repository.proto

package com.example.starter.gprc;

public interface CreateGitRepositoryReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.CreateGitRepositoryReply)
    com.google.protobuf.MessageOrBuilder {
}
