// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session.proto

package com.example.starter.gprc;

public interface GetCurrentSessionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.GetCurrentSessionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sessionToken = 1;</code>
   * @return The sessionToken.
   */
  java.lang.String getSessionToken();
  /**
   * <code>string sessionToken = 1;</code>
   * @return The bytes for sessionToken.
   */
  com.google.protobuf.ByteString
      getSessionTokenBytes();
}
