// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: git-repository.proto

package com.example.starter.gprc;

public interface GetGitRepositoryDirectoryReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.GetGitRepositoryDirectoryReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string repository = 2;</code>
   * @return The repository.
   */
  java.lang.String getRepository();
  /**
   * <code>string repository = 2;</code>
   * @return The bytes for repository.
   */
  com.google.protobuf.ByteString
      getRepositoryBytes();

  /**
   * <code>string directoryPath = 3;</code>
   * @return The directoryPath.
   */
  java.lang.String getDirectoryPath();
  /**
   * <code>string directoryPath = 3;</code>
   * @return The bytes for directoryPath.
   */
  com.google.protobuf.ByteString
      getDirectoryPathBytes();

  /**
   * <code>repeated .helloworld.FileMetadata files = 4;</code>
   */
  java.util.List<com.example.starter.gprc.FileMetadata> 
      getFilesList();
  /**
   * <code>repeated .helloworld.FileMetadata files = 4;</code>
   */
  com.example.starter.gprc.FileMetadata getFiles(int index);
  /**
   * <code>repeated .helloworld.FileMetadata files = 4;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated .helloworld.FileMetadata files = 4;</code>
   */
  java.util.List<? extends com.example.starter.gprc.FileMetadataOrBuilder> 
      getFilesOrBuilderList();
  /**
   * <code>repeated .helloworld.FileMetadata files = 4;</code>
   */
  com.example.starter.gprc.FileMetadataOrBuilder getFilesOrBuilder(
      int index);
}
