// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: git-repository.proto

package com.example.starter.gprc;

public interface GetGitRepositoryDirectoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.GetGitRepositoryDirectoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sessionToken = 1;</code>
   * @return The sessionToken.
   */
  java.lang.String getSessionToken();
  /**
   * <code>string sessionToken = 1;</code>
   * @return The bytes for sessionToken.
   */
  com.google.protobuf.ByteString
      getSessionTokenBytes();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string repository = 3;</code>
   * @return The repository.
   */
  java.lang.String getRepository();
  /**
   * <code>string repository = 3;</code>
   * @return The bytes for repository.
   */
  com.google.protobuf.ByteString
      getRepositoryBytes();

  /**
   * <code>string directoryPath = 4;</code>
   * @return The directoryPath.
   */
  java.lang.String getDirectoryPath();
  /**
   * <code>string directoryPath = 4;</code>
   * @return The bytes for directoryPath.
   */
  com.google.protobuf.ByteString
      getDirectoryPathBytes();
}
