// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: git-repository.proto

package com.example.starter.gprc;

public interface GetGitRepositoryOfUserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.GetGitRepositoryOfUserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .helloworld.GitRepository gitRepositories = 1;</code>
   */
  java.util.List<com.example.starter.gprc.GitRepository> 
      getGitRepositoriesList();
  /**
   * <code>repeated .helloworld.GitRepository gitRepositories = 1;</code>
   */
  com.example.starter.gprc.GitRepository getGitRepositories(int index);
  /**
   * <code>repeated .helloworld.GitRepository gitRepositories = 1;</code>
   */
  int getGitRepositoriesCount();
  /**
   * <code>repeated .helloworld.GitRepository gitRepositories = 1;</code>
   */
  java.util.List<? extends com.example.starter.gprc.GitRepositoryOrBuilder> 
      getGitRepositoriesOrBuilderList();
  /**
   * <code>repeated .helloworld.GitRepository gitRepositories = 1;</code>
   */
  com.example.starter.gprc.GitRepositoryOrBuilder getGitRepositoriesOrBuilder(
      int index);
}
