// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: git-repository.proto

package com.example.starter.gprc;

public final class GitRepositoryProto {
  private GitRepositoryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GitRepository_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GitRepository_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_CreateGitRepositoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_CreateGitRepositoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_CreateGitRepositoryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_CreateGitRepositoryReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GetGitRepositoryOfUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GetGitRepositoryOfUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_GetGitRepositoryOfUserReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_GetGitRepositoryOfUserReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024git-repository.proto\022\nhelloworld\032\nuser" +
      ".proto\"S\n\rGitRepository\022\014\n\004name\030\001 \001(\t\022\024\n" +
      "\014userUserName\030\002 \001(\t\022\036\n\004user\030\003 \001(\0132\020.hell" +
      "oworld.User\"@\n\032CreateGitRepositoryReques" +
      "t\022\014\n\004name\030\001 \001(\t\022\024\n\014sessionToken\030\002 \001(\t\"\032\n" +
      "\030CreateGitRepositoryReply\"G\n\035GetGitRepos" +
      "itoryOfUserRequest\022\020\n\010username\030\001 \001(\t\022\024\n\014" +
      "sessionToken\030\002 \001(\t\"Q\n\033GetGitRepositoryOf" +
      "UserReply\0222\n\017gitRepositories\030\001 \003(\0132\031.hel" +
      "loworld.GitRepository2\323\001\n\024GitRepositoryS" +
      "ervice\022X\n\006Create\022&.helloworld.CreateGitR" +
      "epositoryRequest\032$.helloworld.CreateGitR" +
      "epositoryReply\"\000\022a\n\tGetOfUser\022).hellowor" +
      "ld.GetGitRepositoryOfUserRequest\032\'.hello" +
      "world.GetGitRepositoryOfUserReply\"\000B0\n\030c" +
      "om.example.starter.gprcB\022GitRepositoryPr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.starter.gprc.UserProto.getDescriptor(),
        });
    internal_static_helloworld_GitRepository_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_GitRepository_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GitRepository_descriptor,
        new java.lang.String[] { "Name", "UserUserName", "User", });
    internal_static_helloworld_CreateGitRepositoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_CreateGitRepositoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_CreateGitRepositoryRequest_descriptor,
        new java.lang.String[] { "Name", "SessionToken", });
    internal_static_helloworld_CreateGitRepositoryReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_helloworld_CreateGitRepositoryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_CreateGitRepositoryReply_descriptor,
        new java.lang.String[] { });
    internal_static_helloworld_GetGitRepositoryOfUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_helloworld_GetGitRepositoryOfUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GetGitRepositoryOfUserRequest_descriptor,
        new java.lang.String[] { "Username", "SessionToken", });
    internal_static_helloworld_GetGitRepositoryOfUserReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_helloworld_GetGitRepositoryOfUserReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_GetGitRepositoryOfUserReply_descriptor,
        new java.lang.String[] { "GitRepositories", });
    com.example.starter.gprc.UserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
