// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.example.starter.gprc;

public interface LoginReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.LoginReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.helloworld.Session session = 1;</code>
   * @return Whether the session field is set.
   */
  boolean hasSession();
  /**
   * <code>.helloworld.Session session = 1;</code>
   * @return The session.
   */
  com.example.starter.gprc.Session getSession();
  /**
   * <code>.helloworld.Session session = 1;</code>
   */
  com.example.starter.gprc.SessionOrBuilder getSessionOrBuilder();
}
