// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logout.proto

package com.example.starter.gprc;

public interface LogoutReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.LogoutReply)
    com.google.protobuf.MessageOrBuilder {
}
