// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package com.example.starter.gprc;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string sessionToken = 3;</code>
   * @return The sessionToken.
   */
  java.lang.String getSessionToken();
  /**
   * <code>string sessionToken = 3;</code>
   * @return The bytes for sessionToken.
   */
  com.google.protobuf.ByteString
      getSessionTokenBytes();
}
