// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session.proto

package com.example.starter.gprc;

public final class SessionProto {
  private SessionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_Session_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_Session_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsession.proto\022\nhelloworld\032\nuser.proto\"" +
      "K\n\007Session\022\024\n\014userUsername\030\001 \001(\t\022\n\n\002id\030\002" +
      " \001(\t\022\036\n\004user\030\003 \001(\0132\020.helloworld.UserB*\n\030" +
      "com.example.starter.gprcB\014SessionProtoP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.starter.gprc.UserProto.getDescriptor(),
        });
    internal_static_helloworld_Session_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_Session_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_Session_descriptor,
        new java.lang.String[] { "UserUsername", "Id", "User", });
    com.example.starter.gprc.UserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
