// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: git-repository.proto

package com.jogit.server.gprc;

public interface GetGitRepositoryOfUserReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.GetGitRepositoryOfUserReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .helloworld.GitRepository gitRepositories = 1;</code>
   */
  java.util.List<com.jogit.server.gprc.GitRepository>
      getGitRepositoriesList();
  /**
   * <code>repeated .helloworld.GitRepository gitRepositories = 1;</code>
   */
  com.jogit.server.gprc.GitRepository getGitRepositories(int index);
  /**
   * <code>repeated .helloworld.GitRepository gitRepositories = 1;</code>
   */
  int getGitRepositoriesCount();
  /**
   * <code>repeated .helloworld.GitRepository gitRepositories = 1;</code>
   */
  java.util.List<? extends com.jogit.server.gprc.GitRepositoryOrBuilder>
      getGitRepositoriesOrBuilderList();
  /**
   * <code>repeated .helloworld.GitRepository gitRepositories = 1;</code>
   */
  com.jogit.server.gprc.GitRepositoryOrBuilder getGitRepositoriesOrBuilder(
      int index);
}
