// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logout.proto

package com.jogit.server.gprc;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.LogoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sessionToken = 1;</code>
   * @return The sessionToken.
   */
  java.lang.String getSessionToken();
  /**
   * <code>string sessionToken = 1;</code>
   * @return The bytes for sessionToken.
   */
  com.google.protobuf.ByteString
      getSessionTokenBytes();
}
