// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session.proto

package com.jogit.server.gprc;

public interface SessionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.Session)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userUsername = 1;</code>
   * @return The userUsername.
   */
  java.lang.String getUserUsername();
  /**
   * <code>string userUsername = 1;</code>
   * @return The bytes for userUsername.
   */
  com.google.protobuf.ByteString
      getUserUsernameBytes();

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.helloworld.User user = 3;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.helloworld.User user = 3;</code>
   * @return The user.
   */
  com.jogit.server.gprc.User getUser();
  /**
   * <code>.helloworld.User user = 3;</code>
   */
  com.jogit.server.gprc.UserOrBuilder getUserOrBuilder();
}
