// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.jogit.server.grpc;

public interface AddSshPublicKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.AddSshPublicKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string sessionToken = 2;</code>
   * @return The sessionToken.
   */
  java.lang.String getSessionToken();
  /**
   * <code>string sessionToken = 2;</code>
   * @return The bytes for sessionToken.
   */
  com.google.protobuf.ByteString
      getSessionTokenBytes();

  /**
   * <code>string sshPublicKey = 3;</code>
   * @return The sshPublicKey.
   */
  java.lang.String getSshPublicKey();
  /**
   * <code>string sshPublicKey = 3;</code>
   * @return The bytes for sshPublicKey.
   */
  com.google.protobuf.ByteString
      getSshPublicKeyBytes();
}
