// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.jogit.server.grpc;

/**
 * Protobuf type {@code helloworld.GetSshPublicKeyReply}
 */
public  final class GetSshPublicKeyReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helloworld.GetSshPublicKeyReply)
    GetSshPublicKeyReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetSshPublicKeyReply.newBuilder() to construct.
  private GetSshPublicKeyReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetSshPublicKeyReply() {
    sshPublicKeys_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetSshPublicKeyReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetSshPublicKeyReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              sshPublicKeys_ = new java.util.ArrayList<com.jogit.server.grpc.SshPublicKey>();
              mutable_bitField0_ |= 0x00000001;
            }
            sshPublicKeys_.add(
                input.readMessage(com.jogit.server.grpc.SshPublicKey.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        sshPublicKeys_ = java.util.Collections.unmodifiableList(sshPublicKeys_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jogit.server.grpc.UserProto.internal_static_helloworld_GetSshPublicKeyReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jogit.server.grpc.UserProto.internal_static_helloworld_GetSshPublicKeyReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jogit.server.grpc.GetSshPublicKeyReply.class, com.jogit.server.grpc.GetSshPublicKeyReply.Builder.class);
  }

  public static final int SSHPUBLICKEYS_FIELD_NUMBER = 1;
  private java.util.List<com.jogit.server.grpc.SshPublicKey> sshPublicKeys_;
  /**
   * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
   */
  public java.util.List<com.jogit.server.grpc.SshPublicKey> getSshPublicKeysList() {
    return sshPublicKeys_;
  }
  /**
   * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
   */
  public java.util.List<? extends com.jogit.server.grpc.SshPublicKeyOrBuilder> 
      getSshPublicKeysOrBuilderList() {
    return sshPublicKeys_;
  }
  /**
   * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
   */
  public int getSshPublicKeysCount() {
    return sshPublicKeys_.size();
  }
  /**
   * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
   */
  public com.jogit.server.grpc.SshPublicKey getSshPublicKeys(int index) {
    return sshPublicKeys_.get(index);
  }
  /**
   * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
   */
  public com.jogit.server.grpc.SshPublicKeyOrBuilder getSshPublicKeysOrBuilder(
      int index) {
    return sshPublicKeys_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < sshPublicKeys_.size(); i++) {
      output.writeMessage(1, sshPublicKeys_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < sshPublicKeys_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, sshPublicKeys_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jogit.server.grpc.GetSshPublicKeyReply)) {
      return super.equals(obj);
    }
    com.jogit.server.grpc.GetSshPublicKeyReply other = (com.jogit.server.grpc.GetSshPublicKeyReply) obj;

    if (!getSshPublicKeysList()
        .equals(other.getSshPublicKeysList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSshPublicKeysCount() > 0) {
      hash = (37 * hash) + SSHPUBLICKEYS_FIELD_NUMBER;
      hash = (53 * hash) + getSshPublicKeysList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jogit.server.grpc.GetSshPublicKeyReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jogit.server.grpc.GetSshPublicKeyReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jogit.server.grpc.GetSshPublicKeyReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jogit.server.grpc.GetSshPublicKeyReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jogit.server.grpc.GetSshPublicKeyReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jogit.server.grpc.GetSshPublicKeyReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jogit.server.grpc.GetSshPublicKeyReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jogit.server.grpc.GetSshPublicKeyReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jogit.server.grpc.GetSshPublicKeyReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jogit.server.grpc.GetSshPublicKeyReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jogit.server.grpc.GetSshPublicKeyReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jogit.server.grpc.GetSshPublicKeyReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jogit.server.grpc.GetSshPublicKeyReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helloworld.GetSshPublicKeyReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helloworld.GetSshPublicKeyReply)
      com.jogit.server.grpc.GetSshPublicKeyReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jogit.server.grpc.UserProto.internal_static_helloworld_GetSshPublicKeyReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jogit.server.grpc.UserProto.internal_static_helloworld_GetSshPublicKeyReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jogit.server.grpc.GetSshPublicKeyReply.class, com.jogit.server.grpc.GetSshPublicKeyReply.Builder.class);
    }

    // Construct using com.jogit.server.grpc.GetSshPublicKeyReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSshPublicKeysFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (sshPublicKeysBuilder_ == null) {
        sshPublicKeys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        sshPublicKeysBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jogit.server.grpc.UserProto.internal_static_helloworld_GetSshPublicKeyReply_descriptor;
    }

    @java.lang.Override
    public com.jogit.server.grpc.GetSshPublicKeyReply getDefaultInstanceForType() {
      return com.jogit.server.grpc.GetSshPublicKeyReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.jogit.server.grpc.GetSshPublicKeyReply build() {
      com.jogit.server.grpc.GetSshPublicKeyReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.jogit.server.grpc.GetSshPublicKeyReply buildPartial() {
      com.jogit.server.grpc.GetSshPublicKeyReply result = new com.jogit.server.grpc.GetSshPublicKeyReply(this);
      int from_bitField0_ = bitField0_;
      if (sshPublicKeysBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          sshPublicKeys_ = java.util.Collections.unmodifiableList(sshPublicKeys_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.sshPublicKeys_ = sshPublicKeys_;
      } else {
        result.sshPublicKeys_ = sshPublicKeysBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jogit.server.grpc.GetSshPublicKeyReply) {
        return mergeFrom((com.jogit.server.grpc.GetSshPublicKeyReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jogit.server.grpc.GetSshPublicKeyReply other) {
      if (other == com.jogit.server.grpc.GetSshPublicKeyReply.getDefaultInstance()) return this;
      if (sshPublicKeysBuilder_ == null) {
        if (!other.sshPublicKeys_.isEmpty()) {
          if (sshPublicKeys_.isEmpty()) {
            sshPublicKeys_ = other.sshPublicKeys_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSshPublicKeysIsMutable();
            sshPublicKeys_.addAll(other.sshPublicKeys_);
          }
          onChanged();
        }
      } else {
        if (!other.sshPublicKeys_.isEmpty()) {
          if (sshPublicKeysBuilder_.isEmpty()) {
            sshPublicKeysBuilder_.dispose();
            sshPublicKeysBuilder_ = null;
            sshPublicKeys_ = other.sshPublicKeys_;
            bitField0_ = (bitField0_ & ~0x00000001);
            sshPublicKeysBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSshPublicKeysFieldBuilder() : null;
          } else {
            sshPublicKeysBuilder_.addAllMessages(other.sshPublicKeys_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jogit.server.grpc.GetSshPublicKeyReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jogit.server.grpc.GetSshPublicKeyReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.jogit.server.grpc.SshPublicKey> sshPublicKeys_ =
      java.util.Collections.emptyList();
    private void ensureSshPublicKeysIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        sshPublicKeys_ = new java.util.ArrayList<com.jogit.server.grpc.SshPublicKey>(sshPublicKeys_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jogit.server.grpc.SshPublicKey, com.jogit.server.grpc.SshPublicKey.Builder, com.jogit.server.grpc.SshPublicKeyOrBuilder> sshPublicKeysBuilder_;

    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public java.util.List<com.jogit.server.grpc.SshPublicKey> getSshPublicKeysList() {
      if (sshPublicKeysBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sshPublicKeys_);
      } else {
        return sshPublicKeysBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public int getSshPublicKeysCount() {
      if (sshPublicKeysBuilder_ == null) {
        return sshPublicKeys_.size();
      } else {
        return sshPublicKeysBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public com.jogit.server.grpc.SshPublicKey getSshPublicKeys(int index) {
      if (sshPublicKeysBuilder_ == null) {
        return sshPublicKeys_.get(index);
      } else {
        return sshPublicKeysBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public Builder setSshPublicKeys(
        int index, com.jogit.server.grpc.SshPublicKey value) {
      if (sshPublicKeysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSshPublicKeysIsMutable();
        sshPublicKeys_.set(index, value);
        onChanged();
      } else {
        sshPublicKeysBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public Builder setSshPublicKeys(
        int index, com.jogit.server.grpc.SshPublicKey.Builder builderForValue) {
      if (sshPublicKeysBuilder_ == null) {
        ensureSshPublicKeysIsMutable();
        sshPublicKeys_.set(index, builderForValue.build());
        onChanged();
      } else {
        sshPublicKeysBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public Builder addSshPublicKeys(com.jogit.server.grpc.SshPublicKey value) {
      if (sshPublicKeysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSshPublicKeysIsMutable();
        sshPublicKeys_.add(value);
        onChanged();
      } else {
        sshPublicKeysBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public Builder addSshPublicKeys(
        int index, com.jogit.server.grpc.SshPublicKey value) {
      if (sshPublicKeysBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSshPublicKeysIsMutable();
        sshPublicKeys_.add(index, value);
        onChanged();
      } else {
        sshPublicKeysBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public Builder addSshPublicKeys(
        com.jogit.server.grpc.SshPublicKey.Builder builderForValue) {
      if (sshPublicKeysBuilder_ == null) {
        ensureSshPublicKeysIsMutable();
        sshPublicKeys_.add(builderForValue.build());
        onChanged();
      } else {
        sshPublicKeysBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public Builder addSshPublicKeys(
        int index, com.jogit.server.grpc.SshPublicKey.Builder builderForValue) {
      if (sshPublicKeysBuilder_ == null) {
        ensureSshPublicKeysIsMutable();
        sshPublicKeys_.add(index, builderForValue.build());
        onChanged();
      } else {
        sshPublicKeysBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public Builder addAllSshPublicKeys(
        java.lang.Iterable<? extends com.jogit.server.grpc.SshPublicKey> values) {
      if (sshPublicKeysBuilder_ == null) {
        ensureSshPublicKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sshPublicKeys_);
        onChanged();
      } else {
        sshPublicKeysBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public Builder clearSshPublicKeys() {
      if (sshPublicKeysBuilder_ == null) {
        sshPublicKeys_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        sshPublicKeysBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public Builder removeSshPublicKeys(int index) {
      if (sshPublicKeysBuilder_ == null) {
        ensureSshPublicKeysIsMutable();
        sshPublicKeys_.remove(index);
        onChanged();
      } else {
        sshPublicKeysBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public com.jogit.server.grpc.SshPublicKey.Builder getSshPublicKeysBuilder(
        int index) {
      return getSshPublicKeysFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public com.jogit.server.grpc.SshPublicKeyOrBuilder getSshPublicKeysOrBuilder(
        int index) {
      if (sshPublicKeysBuilder_ == null) {
        return sshPublicKeys_.get(index);  } else {
        return sshPublicKeysBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public java.util.List<? extends com.jogit.server.grpc.SshPublicKeyOrBuilder> 
         getSshPublicKeysOrBuilderList() {
      if (sshPublicKeysBuilder_ != null) {
        return sshPublicKeysBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sshPublicKeys_);
      }
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public com.jogit.server.grpc.SshPublicKey.Builder addSshPublicKeysBuilder() {
      return getSshPublicKeysFieldBuilder().addBuilder(
          com.jogit.server.grpc.SshPublicKey.getDefaultInstance());
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public com.jogit.server.grpc.SshPublicKey.Builder addSshPublicKeysBuilder(
        int index) {
      return getSshPublicKeysFieldBuilder().addBuilder(
          index, com.jogit.server.grpc.SshPublicKey.getDefaultInstance());
    }
    /**
     * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
     */
    public java.util.List<com.jogit.server.grpc.SshPublicKey.Builder> 
         getSshPublicKeysBuilderList() {
      return getSshPublicKeysFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jogit.server.grpc.SshPublicKey, com.jogit.server.grpc.SshPublicKey.Builder, com.jogit.server.grpc.SshPublicKeyOrBuilder> 
        getSshPublicKeysFieldBuilder() {
      if (sshPublicKeysBuilder_ == null) {
        sshPublicKeysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.jogit.server.grpc.SshPublicKey, com.jogit.server.grpc.SshPublicKey.Builder, com.jogit.server.grpc.SshPublicKeyOrBuilder>(
                sshPublicKeys_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        sshPublicKeys_ = null;
      }
      return sshPublicKeysBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:helloworld.GetSshPublicKeyReply)
  }

  // @@protoc_insertion_point(class_scope:helloworld.GetSshPublicKeyReply)
  private static final com.jogit.server.grpc.GetSshPublicKeyReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jogit.server.grpc.GetSshPublicKeyReply();
  }

  public static com.jogit.server.grpc.GetSshPublicKeyReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSshPublicKeyReply>
      PARSER = new com.google.protobuf.AbstractParser<GetSshPublicKeyReply>() {
    @java.lang.Override
    public GetSshPublicKeyReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetSshPublicKeyReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetSshPublicKeyReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetSshPublicKeyReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.jogit.server.grpc.GetSshPublicKeyReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

