// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.jogit.server.grpc;

public interface GetSshPublicKeyReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.GetSshPublicKeyReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
   */
  java.util.List<com.jogit.server.grpc.SshPublicKey> 
      getSshPublicKeysList();
  /**
   * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
   */
  com.jogit.server.grpc.SshPublicKey getSshPublicKeys(int index);
  /**
   * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
   */
  int getSshPublicKeysCount();
  /**
   * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
   */
  java.util.List<? extends com.jogit.server.grpc.SshPublicKeyOrBuilder> 
      getSshPublicKeysOrBuilderList();
  /**
   * <code>repeated .helloworld.SshPublicKey sshPublicKeys = 1;</code>
   */
  com.jogit.server.grpc.SshPublicKeyOrBuilder getSshPublicKeysOrBuilder(
      int index);
}
