// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logout.proto

package com.jogit.server.grpc;

public final class LogoutProto {
  private LogoutProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_LogoutReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_LogoutReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014logout.proto\022\nhelloworld\"%\n\rLogoutRequ" +
      "est\022\024\n\014sessionToken\030\001 \001(\t\"\r\n\013LogoutReply" +
      "2H\n\006Logout\022>\n\006Logout\022\031.helloworld.Logout" +
      "Request\032\027.helloworld.LogoutReply\"\000B&\n\025co" +
      "m.jogit.server.grpcB\013LogoutProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helloworld_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_LogoutRequest_descriptor,
        new java.lang.String[] { "SessionToken", });
    internal_static_helloworld_LogoutReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_LogoutReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_LogoutReply_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
