// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logout.proto

package com.jogit.server.grpc;

public interface LogoutReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.LogoutReply)
    com.google.protobuf.MessageOrBuilder {
}
