// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package com.jogit.server.grpc;

public final class RegisterProto {
  private RegisterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helloworld_RegisterReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helloworld_RegisterReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016register.proto\022\nhelloworld\"K\n\017Register" +
      "Request\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 " +
      "\001(\t\022\024\n\014sessionToken\030\003 \001(\t\"%\n\rRegisterRep" +
      "ly\022\024\n\014sessionToken\030\001 \001(\t2P\n\010Register\022D\n\010" +
      "Register\022\033.helloworld.RegisterRequest\032\031." +
      "helloworld.RegisterReply\"\000B(\n\025com.jogit." +
      "server.grpcB\rRegisterProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helloworld_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helloworld_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_RegisterRequest_descriptor,
        new java.lang.String[] { "Username", "Password", "SessionToken", });
    internal_static_helloworld_RegisterReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helloworld_RegisterReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helloworld_RegisterReply_descriptor,
        new java.lang.String[] { "SessionToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
