// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.jogit.server.grpc;

public interface SshPublicKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.SshPublicKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string userUsername = 3;</code>
   * @return The userUsername.
   */
  java.lang.String getUserUsername();
  /**
   * <code>string userUsername = 3;</code>
   * @return The bytes for userUsername.
   */
  com.google.protobuf.ByteString
      getUserUsernameBytes();

  /**
   * <code>bool deleted = 4;</code>
   * @return The deleted.
   */
  boolean getDeleted();
}
