// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.jogit.server.grpc;

public interface UpdateSshPublicKeyReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.UpdateSshPublicKeyReply)
    com.google.protobuf.MessageOrBuilder {
}
