// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.jogit.server.grpc;

/**
 * Protobuf type {@code helloworld.UpdateSshPublicKeyRequest}
 */
public  final class UpdateSshPublicKeyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helloworld.UpdateSshPublicKeyRequest)
    UpdateSshPublicKeyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateSshPublicKeyRequest.newBuilder() to construct.
  private UpdateSshPublicKeyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateSshPublicKeyRequest() {
    sessionToken_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateSshPublicKeyRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UpdateSshPublicKeyRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sessionToken_ = s;
            break;
          }
          case 18: {
            com.jogit.server.grpc.SshPublicKey.Builder subBuilder = null;
            if (sshPublicKey_ != null) {
              subBuilder = sshPublicKey_.toBuilder();
            }
            sshPublicKey_ = input.readMessage(com.jogit.server.grpc.SshPublicKey.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sshPublicKey_);
              sshPublicKey_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jogit.server.grpc.UserProto.internal_static_helloworld_UpdateSshPublicKeyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jogit.server.grpc.UserProto.internal_static_helloworld_UpdateSshPublicKeyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jogit.server.grpc.UpdateSshPublicKeyRequest.class, com.jogit.server.grpc.UpdateSshPublicKeyRequest.Builder.class);
  }

  public static final int SESSIONTOKEN_FIELD_NUMBER = 1;
  private volatile java.lang.Object sessionToken_;
  /**
   * <code>string sessionToken = 1;</code>
   * @return The sessionToken.
   */
  public java.lang.String getSessionToken() {
    java.lang.Object ref = sessionToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionToken_ = s;
      return s;
    }
  }
  /**
   * <code>string sessionToken = 1;</code>
   * @return The bytes for sessionToken.
   */
  public com.google.protobuf.ByteString
      getSessionTokenBytes() {
    java.lang.Object ref = sessionToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SSHPUBLICKEY_FIELD_NUMBER = 2;
  private com.jogit.server.grpc.SshPublicKey sshPublicKey_;
  /**
   * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
   * @return Whether the sshPublicKey field is set.
   */
  public boolean hasSshPublicKey() {
    return sshPublicKey_ != null;
  }
  /**
   * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
   * @return The sshPublicKey.
   */
  public com.jogit.server.grpc.SshPublicKey getSshPublicKey() {
    return sshPublicKey_ == null ? com.jogit.server.grpc.SshPublicKey.getDefaultInstance() : sshPublicKey_;
  }
  /**
   * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
   */
  public com.jogit.server.grpc.SshPublicKeyOrBuilder getSshPublicKeyOrBuilder() {
    return getSshPublicKey();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSessionTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sessionToken_);
    }
    if (sshPublicKey_ != null) {
      output.writeMessage(2, getSshPublicKey());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSessionTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sessionToken_);
    }
    if (sshPublicKey_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSshPublicKey());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jogit.server.grpc.UpdateSshPublicKeyRequest)) {
      return super.equals(obj);
    }
    com.jogit.server.grpc.UpdateSshPublicKeyRequest other = (com.jogit.server.grpc.UpdateSshPublicKeyRequest) obj;

    if (!getSessionToken()
        .equals(other.getSessionToken())) return false;
    if (hasSshPublicKey() != other.hasSshPublicKey()) return false;
    if (hasSshPublicKey()) {
      if (!getSshPublicKey()
          .equals(other.getSshPublicKey())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSIONTOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getSessionToken().hashCode();
    if (hasSshPublicKey()) {
      hash = (37 * hash) + SSHPUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getSshPublicKey().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jogit.server.grpc.UpdateSshPublicKeyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helloworld.UpdateSshPublicKeyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helloworld.UpdateSshPublicKeyRequest)
      com.jogit.server.grpc.UpdateSshPublicKeyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jogit.server.grpc.UserProto.internal_static_helloworld_UpdateSshPublicKeyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jogit.server.grpc.UserProto.internal_static_helloworld_UpdateSshPublicKeyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jogit.server.grpc.UpdateSshPublicKeyRequest.class, com.jogit.server.grpc.UpdateSshPublicKeyRequest.Builder.class);
    }

    // Construct using com.jogit.server.grpc.UpdateSshPublicKeyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sessionToken_ = "";

      if (sshPublicKeyBuilder_ == null) {
        sshPublicKey_ = null;
      } else {
        sshPublicKey_ = null;
        sshPublicKeyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jogit.server.grpc.UserProto.internal_static_helloworld_UpdateSshPublicKeyRequest_descriptor;
    }

    @java.lang.Override
    public com.jogit.server.grpc.UpdateSshPublicKeyRequest getDefaultInstanceForType() {
      return com.jogit.server.grpc.UpdateSshPublicKeyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.jogit.server.grpc.UpdateSshPublicKeyRequest build() {
      com.jogit.server.grpc.UpdateSshPublicKeyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.jogit.server.grpc.UpdateSshPublicKeyRequest buildPartial() {
      com.jogit.server.grpc.UpdateSshPublicKeyRequest result = new com.jogit.server.grpc.UpdateSshPublicKeyRequest(this);
      result.sessionToken_ = sessionToken_;
      if (sshPublicKeyBuilder_ == null) {
        result.sshPublicKey_ = sshPublicKey_;
      } else {
        result.sshPublicKey_ = sshPublicKeyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jogit.server.grpc.UpdateSshPublicKeyRequest) {
        return mergeFrom((com.jogit.server.grpc.UpdateSshPublicKeyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jogit.server.grpc.UpdateSshPublicKeyRequest other) {
      if (other == com.jogit.server.grpc.UpdateSshPublicKeyRequest.getDefaultInstance()) return this;
      if (!other.getSessionToken().isEmpty()) {
        sessionToken_ = other.sessionToken_;
        onChanged();
      }
      if (other.hasSshPublicKey()) {
        mergeSshPublicKey(other.getSshPublicKey());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jogit.server.grpc.UpdateSshPublicKeyRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jogit.server.grpc.UpdateSshPublicKeyRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object sessionToken_ = "";
    /**
     * <code>string sessionToken = 1;</code>
     * @return The sessionToken.
     */
    public java.lang.String getSessionToken() {
      java.lang.Object ref = sessionToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sessionToken = 1;</code>
     * @return The bytes for sessionToken.
     */
    public com.google.protobuf.ByteString
        getSessionTokenBytes() {
      java.lang.Object ref = sessionToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sessionToken = 1;</code>
     * @param value The sessionToken to set.
     * @return This builder for chaining.
     */
    public Builder setSessionToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sessionToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sessionToken = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionToken() {
      
      sessionToken_ = getDefaultInstance().getSessionToken();
      onChanged();
      return this;
    }
    /**
     * <code>string sessionToken = 1;</code>
     * @param value The bytes for sessionToken to set.
     * @return This builder for chaining.
     */
    public Builder setSessionTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sessionToken_ = value;
      onChanged();
      return this;
    }

    private com.jogit.server.grpc.SshPublicKey sshPublicKey_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jogit.server.grpc.SshPublicKey, com.jogit.server.grpc.SshPublicKey.Builder, com.jogit.server.grpc.SshPublicKeyOrBuilder> sshPublicKeyBuilder_;
    /**
     * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
     * @return Whether the sshPublicKey field is set.
     */
    public boolean hasSshPublicKey() {
      return sshPublicKeyBuilder_ != null || sshPublicKey_ != null;
    }
    /**
     * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
     * @return The sshPublicKey.
     */
    public com.jogit.server.grpc.SshPublicKey getSshPublicKey() {
      if (sshPublicKeyBuilder_ == null) {
        return sshPublicKey_ == null ? com.jogit.server.grpc.SshPublicKey.getDefaultInstance() : sshPublicKey_;
      } else {
        return sshPublicKeyBuilder_.getMessage();
      }
    }
    /**
     * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
     */
    public Builder setSshPublicKey(com.jogit.server.grpc.SshPublicKey value) {
      if (sshPublicKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sshPublicKey_ = value;
        onChanged();
      } else {
        sshPublicKeyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
     */
    public Builder setSshPublicKey(
        com.jogit.server.grpc.SshPublicKey.Builder builderForValue) {
      if (sshPublicKeyBuilder_ == null) {
        sshPublicKey_ = builderForValue.build();
        onChanged();
      } else {
        sshPublicKeyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
     */
    public Builder mergeSshPublicKey(com.jogit.server.grpc.SshPublicKey value) {
      if (sshPublicKeyBuilder_ == null) {
        if (sshPublicKey_ != null) {
          sshPublicKey_ =
            com.jogit.server.grpc.SshPublicKey.newBuilder(sshPublicKey_).mergeFrom(value).buildPartial();
        } else {
          sshPublicKey_ = value;
        }
        onChanged();
      } else {
        sshPublicKeyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
     */
    public Builder clearSshPublicKey() {
      if (sshPublicKeyBuilder_ == null) {
        sshPublicKey_ = null;
        onChanged();
      } else {
        sshPublicKey_ = null;
        sshPublicKeyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
     */
    public com.jogit.server.grpc.SshPublicKey.Builder getSshPublicKeyBuilder() {
      
      onChanged();
      return getSshPublicKeyFieldBuilder().getBuilder();
    }
    /**
     * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
     */
    public com.jogit.server.grpc.SshPublicKeyOrBuilder getSshPublicKeyOrBuilder() {
      if (sshPublicKeyBuilder_ != null) {
        return sshPublicKeyBuilder_.getMessageOrBuilder();
      } else {
        return sshPublicKey_ == null ?
            com.jogit.server.grpc.SshPublicKey.getDefaultInstance() : sshPublicKey_;
      }
    }
    /**
     * <code>.helloworld.SshPublicKey sshPublicKey = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jogit.server.grpc.SshPublicKey, com.jogit.server.grpc.SshPublicKey.Builder, com.jogit.server.grpc.SshPublicKeyOrBuilder> 
        getSshPublicKeyFieldBuilder() {
      if (sshPublicKeyBuilder_ == null) {
        sshPublicKeyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.jogit.server.grpc.SshPublicKey, com.jogit.server.grpc.SshPublicKey.Builder, com.jogit.server.grpc.SshPublicKeyOrBuilder>(
                getSshPublicKey(),
                getParentForChildren(),
                isClean());
        sshPublicKey_ = null;
      }
      return sshPublicKeyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:helloworld.UpdateSshPublicKeyRequest)
  }

  // @@protoc_insertion_point(class_scope:helloworld.UpdateSshPublicKeyRequest)
  private static final com.jogit.server.grpc.UpdateSshPublicKeyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jogit.server.grpc.UpdateSshPublicKeyRequest();
  }

  public static com.jogit.server.grpc.UpdateSshPublicKeyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateSshPublicKeyRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateSshPublicKeyRequest>() {
    @java.lang.Override
    public UpdateSshPublicKeyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UpdateSshPublicKeyRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateSshPublicKeyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateSshPublicKeyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.jogit.server.grpc.UpdateSshPublicKeyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

